### ISSUE TITLE
사용자 인가 관련 기능 구현 

### ISSUE THREAD

**Issue by chaemina** [chaemina/caramella_toyproject#9]
## Description

사용자 인가 관련 기능 구현 

## TO-DO

- [ ] 로그인 여부에 따른 헤더 
- [ ] 로그아웃 버튼 구현 
- [ ] 권한 여부에 따라 리디렉션 처리
